<a href="https://colab.research.google.com/github/Flor-Si/Trabajos/blob/main/TP5-%20N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
#Importar numpy
import numpy as np

In [ ]:
#Ejercicio1 - Arreglo de Ceros con una longitud de 12

In [17]:
array_1=np.zeros(12)
print(array_1)
print(np.zeros(12, dtype=int)) # Le agrege para esta función dtype para que imprima los valores en formato entero y no float "con decimales"
len (array_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]


12

In [ ]:
#Ejercicio2-Arreglo de Log 10 con cero en todas sus posiciones y unn 10 en la posición n°5

In [18]:
array_2=np.zeros(10) #Creamos un array "con todos los elementos en cero excepto la posicion 5 que tenian que tener el valor 10 en dicha posición"
array_2[5]=10 # determino la posición 5 sea igual a 10
print(array_2)
print(np.zeros(10, dtype=int)) # me imprime el array con numeros enteros esto lo realizo por practica
len (array_2)# función LEN cuenta la longitud del arreglo= 10

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
[0 0 0 0 0 0 0 0 0 0]


10

In [ ]:
#Ejercicio3-Arreglo que tenga los números del 10 al 49