<a href="https://colab.research.google.com/github/Flor-Si/Trabajos/blob/main/TP5-%20N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
#Importar numpy
import numpy as np

In [ ]:
#Ejercicio 1 - Arreglo de Ceros con una longitud de 12

In [ ]:
array_1=np.zeros(12)
print(array_1)
print(np.zeros(12, dtype=int)) # Le agrege para esta función dtype para que imprima los valores en formato entero y no float "con decimales"
len (array_1)# función LEN cuenta la longitud del arreglo= 12

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]


12

In [ ]:
#Ejercicio 2-Arreglo de Log 10 con cero en todas sus posiciones y unn 10 en la posición n°5

In [ ]:
array_2=np.zeros(10) #Creamos un array "con todos los elementos en cero excepto la posicion 5 que tenian que tener el valor 10 en dicha posición"
array_2[5]=10 # determino la posición 5 sea igual a 10
print(array_2)
print(np.zeros(10, dtype=int)) # me imprime el array con numeros enteros esto lo realizo por practica
len (array_2)# función LEN cuenta la longitud del arreglo= 10

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
[0 0 0 0 0 0 0 0 0 0]


10

In [ ]:
#Ejercicio 3-Arreglo que tenga los números del 10 al 49

In [ ]:
array_3=np.arange(10,50) # Con la funcion Arrage me muestra todo lo que se encuentra entre el rango 10 al 50 excluyendo en este caso el ultimo valor por eso ponemos 50
print(array_3)
len(array_3)#Longitud del array

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


40

In [ ]:
#Ejercicio 4-Arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [ ]:
#Acá primero vamos a definir el rango de los valor a utilizar como en el ejercicio anterior con ARANGE
np.arange(9)
print(np.arange(9))# vemos que el arreglo esta en 1 dimension , pero nos esta solicitando la consigna que sea en 2 D de (3X3 ) entonces utilizamos "rshape" para que lo ponga como matriz
array_4= np.arange(9).reshape(3,3)
print(array_4) # Obtuvimo un Arreglo de 2 dimensiones con tres filas y tres columnas con los valores de "Cero al 8"

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Ejercicio 5- Arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [ ]:
array_5=np.random.rand(100) #utilizamos la función aleatoria=random y rand termina hasta que valor toma
print(array_5)
array_media=np.median(array_5) #utilizamos la función media contemplando el array_5 hasta 100 para determinar la media de dicho arreglo
print(array_media)
array_varianza=np.var(array_5) #utilizamos la función varianza contemplando el array_5 hasta 100 para determinar la media de dicho arreglo
print(array_varianza)


[0.92937112 0.38183862 0.05803091 0.90751139 0.01413377 0.06729283
 0.02648012 0.84943504 0.38764921 0.30293053 0.96417038 0.29962321
 0.07190479 0.85151211 0.36068747 0.86644661 0.24556556 0.95277845
 0.10822129 0.43792576 0.34473834 0.24016036 0.4107513  0.48549546
 0.25820752 0.65022949 0.57979267 0.42102856 0.31864075 0.88107379
 0.1031796  0.34770891 0.62836885 0.6735373  0.91736668 0.3389014
 0.63018599 0.11130696 0.51965735 0.17787623 0.6704807  0.07476998
 0.72319109 0.72132961 0.53590395 0.73805859 0.75217811 0.9342498
 0.41792842 0.71882247 0.2059053  0.04874267 0.11154231 0.43159932
 0.97560422 0.05687194 0.98545351 0.32208959 0.78342107 0.36179249
 0.15615759 0.8870857  0.83523068 0.78210452 0.00348341 0.35613591
 0.35835063 0.09937503 0.14359607 0.86517236 0.37060911 0.74359626
 0.53711362 0.28658603 0.99216938 0.89191805 0.76962699 0.06125807
 0.78186431 0.33604927 0.58253934 0.03079195 0.0184593  0.95119808
 0.07614402 0.24264244 0.73537103 0.7357561  0.8277678  0.699353

In [ ]:
#Ejercicio 6- Calcular la media de un arreglo usando np.sum

In [ ]:
lista1=[1,2,3,4,5,6] #Acá partimos desde crear la lista luego la transformamos en un arreglo , sumamos los valores que tenemos dentro del arreglo y determinamos la media del mismo
array_6=np.array(lista1)
print(array_6)
suma=np.sum(array_6)# Funcion Suma del arreglo "6" relizamos la validación
print(suma)
media=np.mean(array_6)#Funcion media del arreglo "6"
print(media)
media_2=suma/len(array_6)
print(media_2)

array_media=np.sum(array_6)/len(array_6) #Ejecutamos lo que nos solicita el enunciado por lo que utilizamos la suma del arreglo y dividimos dicha suma por la funcion LEN que en este caso es "6" cant elementos
print(array_media)


[1 2 3 4 5 6]
21
3.5
3.5
3.5


In [ ]:
#Ejercicio 7- Calcular la varianza de un arreglo usando np.sum y np.mean

In [35]:
lista2=[8,9,10,11,12,13]
array_7=np.array(lista2)

print(array_7)
len(array_7)
print(np.var(array_7))
#realizamos un paso a paso de la función
array_suma=np.sum(array_7)
print(array_suma)
array_media=np.mean(array_7)
print(array_media)
diferencia=array_7-array_media
print(diferencia)
diferencia_cuadrada=diferencia**2
print(diferencia_cuadrada)
suma_cuadrada=np.sum(diferencia_cuadrada)
print(suma_cuadrada)
varianza=suma_cuadrada/len(array_7)
print(varianza)
#Sabemos que la función varianza es igual a la diferencia del arreglo menos la media elevada al cuadrado , dividio por el total de elementos

#Volvemos a replicar lo calculado pero con las formulas de manera más compacta como lo pide el enunciado ,utilizando np. sumy np.mean
varianza=np.sum((array_7 - np.mean(array_7)) ** 2) / len(array_7)
print(varianza)


[ 8  9 10 11 12 13]
2.9166666666666665
63
10.5
[-2.5 -1.5 -0.5  0.5  1.5  2.5]
[6.25 2.25 0.25 0.25 2.25 6.25]
17.5
2.9166666666666665
2.9166666666666665
